version: '3.7'

services:
  bot:
#    environment:
#      - PYTHONPATH=/jopsbank
    container_name: jopsbank
    build: .
    #restart: always
    env_file:
      - .env
    volumes:
      - ./logs/:/app/logs